name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Check if Pages is enabled
      id: check-pages
      run: |
        echo "Checking if GitHub Pages is enabled..."
        # This will be handled by the configure-pages action
        
    - name: Setup Pages
      id: setup-pages
      uses: actions/configure-pages@v4
      continue-on-error: true
      
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: steps.setup-pages.outcome == 'success'
      
    - name: Pages Not Enabled
      if: steps.setup-pages.outcome == 'failure'
      run: |
        echo "❌ GitHub Pages is not enabled in repository settings"
        echo "Please follow these steps:"
        echo "1. Go to your repository Settings"
        echo "2. Click on 'Pages' in the left sidebar"
        echo "3. Set Source to 'GitHub Actions'"
        echo "4. Save the settings"
        echo "5. Re-run this workflow"
        exit 1
